
---
  - name: Install Fish
    apt:
      name: fish
    when: ansible_distribution == 'Ubuntu'
    become: yes

  # - name: Install Fish - set Fish as deafault shell
  #   shell: chsh -s /usr/bin/fish
  #   when: ansible_distribution == 'Ubuntu'
  #   become: yes

  - name: Install Fish - removing default message
    file:
      path:  ~/.config/fish
      state: directory
      mode: 0775
    file:
      path: ~/.config/fish/config.fish
      state: touch
      mode: 0664
    shell: echo 'set -g -x fish_greeting ""' >> ~/.config/fish/config.fish
    when: ansible_distribution == 'Ubuntu'

  - name: Install Fish - install oh my fish
    shell: curl -L https://get.oh-my.fish | fish
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Fish - install simple-ass-prompt theme
    shell: omf install simple-ass-prompt
    when: ansible_distribution == 'Ubuntu'
