---
  - name: Install Fish - add repository
    apt_repository:
      repo: 'ppa:fish-shell/release-2'
      update_cache: yes
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Fish - install
    apt:
      name: fish
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Fish - set Fish as deafault shell
    expect:
      command: "chsh -s /usr/bin/fish"
      responses:
        (?i)password: "{{ ansible_become_pass }}"

  - name: Install Fish - Create config directory
    file:
      path:  ~/.config/fish
      state: directory
      mode: 0775

  - name: Install Fish - Remove welcome message
    lineinfile:
      path: ~/.config/fish/config.fish
      create: yes
      mode: 0664
      insertafter: EOF
      line: set -gx fish_greeting ""
      state: present

  # - name: Install Fish - install oh my fish
  #   shell: "curl -L https://get.oh-my.fish | fish"
  #   when: ansible_distribution == 'Ubuntu'
  #   become: yes
  #
  # - name: Install Fish - install simple-ass-prompt theme
  #   shell: omf install simple-ass-prompt
  #   when: ansible_distribution == 'Ubuntu'
