
---
  - name: Check if {{ fish_package }} is installed
    command: dpkg-query -W {{ fish_package }}
    register: fish_package_check_deb
    failed_when: fish_package_check_deb.rc > 1
    changed_when: fish_package_check_deb.rc == 1

  - name: Download {{ fish_package }}
    get_url:
      url: "{{ fish_url }}"
      dest: /home/"{{ ansible_env.USER }}"/Downloads/"{{ fish_package }}".deb
    when: fish_package_check_deb.rc == 1

  - name: Install {{ fish_package }}
    apt:
      deb: /home/"{{ ansible_env.USER }}"/Downloads/"{{ fish_package }}".deb
    when: fish_package_check_deb.rc == 1
    become: yes
  # - name: Install Fish - set Fish as deafault shell
  #   shell: chsh -s /usr/bin/fish
  #   when: ansible_distribution == 'Ubuntu'
  #   become: yes

  - name: Install Fish - Create config directory
    file:
      path:  ~/.config/fish
      state: directory
      mode: 0775

  - name: Install Fish - Create config file
    file:
      path: ~/.config/fish/config.fish
      state: touch
      mode: 0664

  - name: Install Fish - Remove welcome message
    shell: echo 'set -g -x fish_greeting ""' >> ~/.config/fish/config.fish

  - name: Install Fish - install oh my fish
    shell: "curl -L https://get.oh-my.fish | fish"
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Fish - install simple-ass-prompt theme
    shell: omf install simple-ass-prompt
    when: ansible_distribution == 'Ubuntu'
