---
  - name: Install Mysql Server
    apt:
      name: {{ item }}
      update_cache: yes
      state: installed
    when: ansible_distribution == 'Ubuntu'
    become: yes
    with_items:
     - mysql-server
     - mysql-client
     - python-mysqldb
     - libmysqlclient-dev

  - name: Start the MySQL service
    become: yes
    service:
      name: mysql
      state: started

  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user:
      name: root
      host: local
      password: password
      login_user: root
      login_password: password
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
