---
- name: Write gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Create symlink to gitignore
  file:
    src: "{{ role_path }}"/files/.gitignore
    dest: ~/.gitignore
    state: link
