---
  - name: "Install chrome - ensure Google linux signing key present"
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: "Install chrome - ensure Google chrome repo present"
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: "google-chrome"
      state: present
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: "Install chrome - ensure Google chrome present"
    apt:
      name: google-chrome-stable
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes
