---
  - name: Install VirtualBox - add apt key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install VirtualBox - add repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian xenial contrib"
      state: present
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install VirtualBox
    apt:
      name: virtualbox-5.2
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install dkms
    apt:
      name: dkms
    when: ansible_distribution == 'Ubuntu'
    become: yes
