---
  - name: Add repo
    apt_repository:
      repo: 'ppa:longsleep/golang-backports'
      update_cache: yes
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Go
    apt:
      name: golang-go
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Create workspace for Go projects
    file:
      path:  ~/.go/bin
      state: directory
      mode: 0775
