
---
  - name: Install Tilix - add repo
    apt_repository:
      repo: 'ppa:webupd8team/terminix'
      update_cache: yes
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Tilix - install
    apt:
      name: tilix
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install Tilix - Fix VTE issue (create symlink)
    file:
      src: /etc/profile.d/vte-2.91.sh
      dest: /etc/profile.d/vte.sh
      state: link
    when: ansible_distribution == 'Ubuntu'
    become: yes

  # - name: Install Tilix - set Tilix as deafault terminal
  #   shell: gsettings set org.gnome.desktop.default-applications.terminal exec tilix
  #   when: ansible_distribution == 'Ubuntu'
