---
  - name: Add repo
    apt_repository:
      repo: 'ppa:webupd8team/terminix'
      update_cache: yes
      state: present
    when: ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install
    apt:
      name: tilix
    when: ansible_distribution == 'Ubuntu'
    become: yes

  # - name: Install Tilix - Fix VTE issue (create symlink)
  #   file:
  #     src: /etc/profile.d/vte-2.91.sh
  #     dest: /etc/profile.d/vte.sh
  #     state: link
  #   when: ansible_distribution == 'Ubuntu'
  #   become: yes

  - name: Set Tilix as default terminal
    shell: gsettings set org.gnome.desktop.default-applications.terminal exec tilix
    when: ansible_distribution == 'Ubuntu'

  - name: Add solarized-dark-higher-contrast theme
    file:
      src: "{{ role_path }}/files/tilix"
      dest: ~/.config/tilix
      state: link

  - name: Load tilix configuration
    shell: dconf load /com/gexperts/Tilix/ < "{{ role_path }}/files/tilix.dconf"
    when: ansible_distribution == 'Ubuntu'
