---
  - name: Create symlink to .vim
    file:
      src: "{{ role_path }}/files/.vim"
      dest: ~/.vim
      state: link

  - name: Create symlink to .vimrc
    file:
      src: "{{ role_path }}/files/.vimrc"
      dest: ~/.vimrc
      state: link
